name: Provision Environment From CodeMeta Signatures
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install Detected System/APT Requirements
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - htop
        - python3
        - python3-pip
        - r-base
    - name: Install Detected Python/PIP Dependencies
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - Flask
        - PyYAML
        - matplotlib
        - networkx
        - pandas
        - rdflib
        - requests
        - streamlit